### ISSUE TITLE
Parallelize Http Requests

### ISSUE THREAD

**Issue by haroldhues** [semdiffdotnet/semdiff#24]
Currently, we request the list of pull requests. From there we have a lot of requests that we know we are going to make. The way we process this list is to send one request, then wait for the response before sending the next. However we can use the asynchronous features of the framework to send a lot of requests in parallel and wait on the response at once.

**Comment by cartermp** [comment]
Sounds like a fine time to break out async lambdas for ultimate LINQ-age!  :smiley: 

```csharp
var responses = urls.Select(async url => await DoNetWorkStuff(url));
var results = await responses;
```
