### ISSUE TITLE
Handle Line Ending Differences

### ISSUE THREAD

**Issue by haroldhues** [semdiffdotnet/semdiff#53]
On my machine I have discovered that the files that we retrieve from GitHub have `\n` endings while files from VS have `\r\n` endings. When they are diffed this results in lots of changes indicating that `\r`s were added on each line. This clobbers some of the real changes and prevents False-Positive detection

We will need to investigate if the `\r` will always be added or if this could differ with other setups.

**Comment by MRose90** [comment]
Line ending enum is now included in the configuration. Use this for implementation.
